name: api-service-calls
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API Service
        run: |
          curl https://hugh-onf.vercel.app/api/api_service_calls